name: Tagging workflow.

on:
  push:
    branches:
      - main
      - develop
      - master
      - release

jobs:
  tag-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false

      - uses: MumeiShashinka/ghatest/actions/tag-deployment@develop
        with:
          suffix: ''
          dev-branch: main
